### PR TITLE
Replace auto scaling group resource by equivalent cloudformation stack

### PR DESCRIPTION
**Pull request by miguelaferreira**
This PR replaces the auto scaling group resource by a cloud formation stack resource that creates an equivalent auto scaling group. The cloud formation stack provides extra orchestration abilities when the auto scaling group needs to change, in the form of update policies. The chosen policy is auto scaling rolling update and that triggers a controlled update of instance batches when, for instance, a new AMI is set in the launch configuration. See http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html for the documentation of update policies.

This alone is not yet enough to have zero downtime deployments but it's a step in that direction. The piece of automation that is missing is to trigger container instance draining state before an instance is terminated (as part of the rolling update process). I will work on that next, following the approach described here https://aws.amazon.com/de/blogs/compute/how-to-automate-container-instance-draining-in-amazon-ecs/.
I'll make a generic and open-source lambda function to drain the container instances as part of the auto scaling lifecycle, and make a new PR to this module to integrate that.

When applying a plan with a changed launch configuration (e.g. changed AMI) terraform will wait until the update of all instances is complete. If anything fails in the update process, the cloud formation stack will automatically rollback the update, printing a message like this:
```
Error: Error applying plan:

1 error(s) occurred:

* module.ecs_cluster.module.container_service_cluster.aws_cloudformation_stack.autoscaling_group: 1 error(s) occurred:

* aws_cloudformation_stack.autoscaling_group: UPDATE_ROLLBACK_COMPLETE: ["Received 0 SUCCESS signal(s) out of 1.  Unable to satisfy 100% MinSuccessfulInstancesPercent requirement"]

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### CODE REVIEW

**Comment by hectcastro** [comment]
@miguelaferreira, just wanted to start off by saying that we sincerely appreciate the effort you've put in to making this module better than it was when you found it.

Specific to this PR, we have some concerns with the approach taken at a high level. Not because we think it is flawed—we've used the rolling ASG update mechanism with CloudFormation in the past, and we also drain ECS cluster after launch configuration AMI changes (manually). More so because we have been moving away from CloudFormation as an organization, and would prefer to keep reusable modules away from using both technologies (Terraform and CloudFormation) to solve a problem.

I also think that there is some general concern over the level of automation required for this end-to-end solution to work. As I mentioned before, we currently do the draining process manually, which isn't ideal, but it is what we have the most confidence with after assessing some automated alternatives.

**Comment by miguelaferreira** [comment]
@hectcastro Thanks for getting back to me. I was hoping you would find this useful but I also expected that that you didn't. It's quite an involved change and does have significant impact on how to operate the cluster. For me it will in the end make things easier since I don't want to/sometimes can't be doing manual operations on the cluster.

Anyway, I will close this PR and continue my work on a fork of this module, if you don't mind.

**Comment by hectcastro** [comment]
That course of action sounds acceptable to me. Definitely keep in touch though. We'd love to collaborate in other ways to improve how ECS clusters are managed with Terraform (especially now that Fargate and Kubernetes are being added to the mix).

**Comment by miguelaferreira** [comment]
Thanks for understanding. I'll keep making PRs to this module whenever I find an opportunity. Much in the same way I'll pull improvements from here if they fit my work.

**Pull request closed without merging**
